### ISSUE TITLE
implement registration

### ISSUE THREAD

**Issue by vilnacrm** [VilnaCRM-Org/user-service#1]
As a new user i want to be able to register on the system through credentials (initials, email, password) or through social networks (google, facebook, twitter, github)

### Technical requirements

- [ ] PHP 8.1
- [ ] API platform 3
- [ ] OAuth server

### Tasks

- [ ] init [user service](https://github.com/VilnaCRM-Org/user-service)
- [ ] set up docker for service
- [ ] set up CI checks using Github actions (phpstan, phpcs and etc.)
- [ ] implement registration endpoint using credentials (REST API, GraphQL)
- [ ] implement OAuth server
- [ ] implement registration through social networks
- [ ] implement sending the confirmation email
- [ ] check that swagger documentation looks good
- [ ] cover the code with auto-tests

### Acceptance criteria

- [ ] API endpoint allows to register new user with credentials
- [ ] API endpoint allows to register new user through social networks
- [ ] new user receives a confirmation email
- [ ] all backend tests passed
