### ISSUE TITLE
implement user registration

### ISSUE THREAD

**Issue by Kravalg** [VilnaCRM-Org/user-service#1]
As a user, I want to be able to register in the VilnaCRM.

[Design](https://www.figma.com/file/hubQLvQkAlz8wWs2C60T3p/VilnaCRM?type=design&node-id=0-1&t=KiZ8Iq6wInNqRgPb-0)

[User flow](https://miro.com/app/board/uXjVPQ3J5kI=/?share_link_id=531477366176)

[Architecture](https://miro.com/app/board/uXjVPRE64mI=/)

### Technical requirements

- [x] PHP 8
- [x] API platform 3
- [x] MariaDB
- [x] AWS ElastiCache (Redis)
- [x] Symfony Messenger
- [x] Symfony Mailer
- [x] [OAuth server](https://github.com/thephpleague/oauth2-server-bundle)

### Tasks

- [x] Design architecture for C4 model
- [x] Add MariaDB to the docker
- [x] Implement REST API endpoint for user registration (will be used by Administration panel, SDK, CMS plugins)
- [x] Implement GraphQL endpoint for user registration (will be used by Frontend)
- [x] Implement sending the email to the new user
- [x] Implement REST API, GraphQL endpoint for confirming user email
- [x] Implement CRUD endpoints for users
- [x] Add and configure the OAuth server 
- [x] Add logging for email sending command handler
- [x] Add documentation for REST API OAuth server endpoints
- [x] Write to the issue comments information about endpoints names and GraphQL queries/mutations
- [x] Add retry logic for sending emails more than one attempt (check @pixelTM [comment](https://github.com/VilnaCRM-Org/user-service/issues/1#issuecomment-1621853783))
- [x] Cover code by autotests *
- [x] Move architecture diagrams to [structurizr](https://structurizr.com/)
- [x] rewrite load tests from artillery to the [k6](https://github.com/grafana/k6)

"* - optional"

### Acceptance criteria

- [x] User can be registered through REST API, GraphQL endpoints
- [x] CRUD for user works through REST API
- [x] OAuth server configured and allow third-party applications to work with our API
- [x] User can confirm email through REST API, GraphQL endpoints
- [x] Issue comments exist with information about endpoints names and GraphQL queries/mutations
- [x] All tests passed

**Comment by Kravalg** [comment]
Deadline: 02 July (40 hours)

**Comment by pixelTM** [comment]
@Kravalg  Need add retry send confirm email, and need limit retry send email by time. First retry - 1 min, second - 3 min, 3th - 5 min. If user request 4th retry send email, user take ban on 24 hour

**Comment by kukuruzvelt** [comment]
mutation {
  registerUserGraphQL(
    input: {
      email: "eraaaafarg@gmail.com"
      initials: "U"
      password: "ad"
    }
  ) {
    user {
      id
      email
      initials
    }
  }
}

**Comment by kukuruzvelt** [comment]
`mutation {
registerUserGraphQL(
input: {
email: "[eraaaafarg@gmail.com](mailto:eraaaafarg@gmail.com)"
initials: "U"
password: "ad"
}
) {
user {
id
email
initials
}
}
}`

**Comment by Kravalg** [comment]
**GraphQL**

Endpoint - `/api/graphql`

Request body
```
mutation {
  registerUser(
    input: { email: "eraaaafarg@gmail.com", initials: "Huan Karlos FIniat", password: "ad" }
  ) {
    user {
      id
      email
      initials
    }
  }
}

```

**REST API**

Endpoint - POST /api/users

Request body
```
{
  "email": "user@example.com",
  "initials": "string",
  "password": "string"
}
```

Response body
```
{
  "@context": "string",
  "@id": "string",
  "@type": "string",
  "id": "string",
  "email": "user@example.com",
  "initials": "string",
}
```

**Comment by vilnacrm** [comment]
> @Kravalg Need add retry send confirm email, and need limit retry send email by time. First retry - 1 min, second - 3 min, 3th - 5 min. If user request 4th retry send email, user take ban on 24 hour

We don't have the design for UI where user can retry sending the email messages.
But we can implement it on the backend side [https://symfony.com/doc/current/messenger.html#retries-failures](https://symfony.com/doc/current/messenger.html#retries-failures)

**Comment by Kravalg** [comment]
test

**Comment by Kravalg** [comment]
API Service contract @pixelTM 

https://github.com/VilnaCRM-Org/user-service/wiki/API-Endpoints
