### ISSUE TITLE
fix CI issues

### ISSUE THREAD

**Issue by Derane** [VilnaCRM-Org/user-service#16]
### Description
Need to fix README.md file
### Tasks
- [ ] fix open-api-diff pipeline
- [ ] fix Generate Changelog and Create Release
### Acceptance Criteria
- [ ] CI have no error
