### ISSUE TITLE
implement authentication

### ISSUE THREAD

**Issue by vilnacrm** [VilnaCRM-Org/user-service#2]
As a user i want to be able to login on the system through credentials (email, password, 2FA code) or through social networks (google, facebook, twitter, github)

### Technical requirements

- [ ] PHP 8.1
- [ ] API platform 3
- [ ] OAuth

### Tasks

- [ ] init [user service](https://github.com/VilnaCRM-Org/user-service)
- [ ] set up docker for service
- [ ] set up CI checks using Github actions (phpstan, phpcs and etc.)
- [ ] implement auth endpoint using credentials (REST API, GraphQL)
- [ ] implement OAuth authentication for API clients
- [ ] implement auth endpoint for social networks
- [ ] implement 2FA authentication
- [ ] check that swagger documentation looks good
- [ ] cover the code with auto-tests

### Acceptance criteria

- [ ] API endpoint allows to log in user with credentials
- [ ] API endpoint allows to log in user through social networks
- [ ] API endpoint allows to log in API client through access token
- [ ] 2FA should works
- [ ] all backend tests passed
