### ISSUE TITLE
implement restore password

### ISSUE THREAD

**Issue by vilnacrm** [VilnaCRM-Org/user-service#3]
As an existed user i want to be able to restore password on the system through email

### Tasks

- [ ] implement restore password endpoint using credentials (REST API, GraphQL)
- [ ] implement 2FA support
- [ ] check that swagger documentation looks good
- [ ] cover the code with auto-tests

### Acceptance criteria

- [ ] API endpoint allows to restore password endpoint
- [ ] 2FA should works
- [ ] check that swagger documentation looks good
- [ ] all backend tests passed
